#!/bin/sh

# Set these paths appropriately

BIN=/mnt/c/Users/Kevin/source/repos/DEFT/treetagger/bin
CMD=/mnt/c/Users/Kevin/source/repos/DEFT/treetagger/cmd
LIB=/mnt/c/Users/Kevin/source/repos/DEFT/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/galician-abbreviations-utf8
PARFILE=${LIB}/galician-utf8.par
MWLFILE=${LIB}/galician-mwls

$TOKENIZER -z -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
